### ISSUE TITLE
Comment accéder à tes jeux ?

### ISSUE THREAD

**Issue by elig-45** [Audrey88/jeux#1]
Peux-tu activer GitHub Pages sur ton projet et afficher le lien sur la présentation du projet pour qu’on puisse tester tes jeux ?

*Merci,*

**EliG-45**

**Comment by Audrey88** [comment]
Bonjour, j'ai activé GitHub Pages sur ce projet. Les jeux jouable se situent dans le dossier jeux, chaque page html est un jeu. 

Bon amusement!

**Comment by elig-45** [comment]
Pourquoi ne pas juste activer GitHub pages pour obtenir une adresse.io qui contiendrait les jeux?

Eli G

Envoyé de mon iPad EA

**Comment by Audrey88** [comment]
J'ai activé, cela fait un moment que je ne suis plus sur github je ne me rappel plus de toutes ses fonctionnalités. De plus, ces projets sont mes débuts dans la programmation : 
http://audrey88.github.io/jeux/

**Comment by elig-45** [comment]
Ok. Pas de souci.

Eli G

Envoyé de mon iPad EA
